# Generated by Django 5.1.1 on 2024-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='title',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_origin',
            field=models.CharField(default='ACT Government Website', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='Canberra', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='position_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
